### ISSUE TITLE
Is Internal/public check?

### ISSUE THREAD

**Issue by mynameistechno** [qualcomm/qcom-actions#5]
I noticed the dependency review check fails for private repos that don't have it enabled (We only enable github security on public repos)

https://github.com/qualcomm/qualcomm-k8s-device-plugins/actions/runs/15785489843/job/44500862067?pr=2

For add a conditional check if the current repo is private, copilot suggested 

```yml
jobs:
  check-repo-visibility:
    runs-on: ubuntu-latest
    outputs:
      is_private: ${{ steps.get_visibility.outputs.is_private }}
    steps:
      - name: Get repository visibility
        id: get_visibility
        run: |
          visibility=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} | jq -r '.private')
          echo "is_private=$visibility" >> $GITHUB_OUTPUT

  conditional-job:
    needs: check-repo-visibility
    if: needs.check-repo-visibility.outputs.is_private == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Run only for private repos
        run: echo "This step runs only if the repo is private."

```
